[package]
name = "JASS-Tree-sitter-Rust"
version = "0.2.0"
authors = ["nazarpunk <nazarpunk@gmail.com>"]
edition = "2021"

[dependencies]
tree-sitter = "0.25.3"
tree-sitter-lua = { path = "./../tree-sitter-lua" }

[build-dependencies]


