use num_enum::{IntoPrimitive, TryFromPrimitive};

/// Node type IDs from `ts_symbol_identifiers` enum in tree-sitter-jass `parser.c`.
#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, TryFromPrimitive, IntoPrimitive)]
pub enum Kind {
    // anonymous / terminal symbols
    Loop = 1,
    Endloop = 2,
    Constant = 3,
    Array = 4,
    Comma = 5,
    Equal = 6,
    LeftBracket = 7,
    RightBracket = 8,
    PlusPlus = 9,
    MinusMinus = 10,
    Not = 11,
    Minus = 12,
    Plus = 13,
    Star = 14,
    Slash = 15,
    Lt = 16,
    Gt = 17,
    Le = 18,
    Ge = 19,
    EqEq = 20,
    Neq = 21,
    And = 22,
    Or = 23,
    Number = 24,
    Float = 25,
    Quote = 26,
    Return = 27,
    Exitwhen = 28,
    Local = 29,
    Set = 30,
    Call = 31,
    If = 32,
    Then = 33,
    Elseif = 34,
    Else = 35,
    Endif = 36,
    Native = 37,
    Takes = 38,
    Nothing = 39,
    Returns = 40,
    Type = 41,
    Extends = 42,
    Function = 43,
    Endfunction = 44,
    Globals = 45,
    Endglobals = 46,
    LeftParen = 47,
    RightParen = 48,
    Comment = 49,
    StringContent = 50,
    EscapeSequence = 51,
    Rawcode = 52,
    IdToken = 53,

    // named / non-terminal symbols
    Program = 58,
    Id = 59,
    //_Statement = 60,
    LoopStatement = 61,
    VarStmt = 62,
    VarDecl = 63,
    Expr = 64,
    StringLiteral = 65,
    ReturnStatement = 66,
    ExitwhenStatement = 67,
    LocalStatement = 68,
    SetStatement = 69,
    CallStatement = 70,
    IfStatement = 71,
    NativeStatement = 72,
    TypeStatement = 73,
    FunctionStatement = 74,
    GlobalsBlock = 75,
    ParameterList = 76,
    Parameter = 77,
    FunctionRef = 78,
    Parens = 79,
    FunctionCall = 80,
    FunctionArguments = 81,
}

/// Field IDs from `ts_field_identifiers` enum in tree-sitter-jass `parser.c`.
#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, TryFromPrimitive, IntoPrimitive)]
pub enum Field {
    Args = 1,
    Base = 2,
    Condition = 3,
    Index = 4,
    Name = 5,
    Parameters = 6,
    ReturnType = 7,
    Type = 8,
    Value = 9,
    Variable = 10,
}

