use num_enum::{IntoPrimitive, TryFromPrimitive};

/// Node type IDs from `ts_symbol_identifiers` enum in tree-sitter-jass `parser.c`.
#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, TryFromPrimitive, IntoPrimitive)]
pub enum Kind {
    // anonymous / terminal symbols
    Loop = 1,
    Endloop = 2,
    Constant = 3,
    Array = 4,
    Comma = 5,
    Equal = 6,
    LeftBracket = 7,
    RightBracket = 8,
    PlusPlus = 9,
    MinusMinus = 10,
    Not = 11,
    Minus = 12,
    Plus = 13,
    Star = 14,
    Slash = 15,
    Lt = 16,
    Gt = 17,
    Le = 18,
    Ge = 19,
    EqEq = 20,
    Neq = 21,
    And = 22,
    Or = 23,
    Number = 24,
    Float = 25,
    Quote = 26,
    Return = 27,
    Exitwhen = 28,
    Local = 29,
    Set = 30,
    Call = 31,
    If = 32,
    Then = 33,
    Elseif = 34,
    Else = 35,
    Endif = 36,
    Native = 37,
    Takes = 38,
    Nothing = 39,
    Returns = 40,
    Type = 41,
    Extends = 42,
    Function = 43,
    Endfunction = 44,
    Globals = 45,
    Endglobals = 46,
    LeftParen = 47,
    RightParen = 48,
    Comment = 49,
    StringContent = 50,
    Rawcode = 51,
    IdToken = 52,

    // named / non-terminal symbols
    Program = 57,
    Id = 58,
    //_Statement = 59,
    LoopStatement = 60,
    VarStmt = 61,
    VarDecl = 62,
    Expr = 63,
    StringLiteral = 64,
    ReturnStatement = 65,
    ExitwhenStatement = 66,
    LocalStatement = 67,
    SetStatement = 68,
    CallStatement = 69,
    IfStatement = 70,
    NativeStatement = 71,
    TypeStatement = 72,
    FunctionStatement = 73,
    GlobalsBlock = 74,
    ParameterList = 75,
    Parameter = 76,
    FunctionRef = 77,
    Parens = 78,
    FunctionCall = 79,
    FunctionArguments = 80,
}

/// Field IDs from `ts_field_identifiers` enum in tree-sitter-jass `parser.c`.
#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, TryFromPrimitive, IntoPrimitive)]
pub enum Field {
    Args = 1,
    Base = 2,
    Condition = 3,
    Index = 4,
    Name = 5,
    Parameters = 6,
    ReturnType = 7,
    Type = 8,
    Value = 9,
    Variable = 10,
}

